services:
  # Backend service
  - type: web
    name: postcode-clustering-api
    env: python
    buildCommand: pip install -r requirements.txt  # Build command for backend
    startCommand: gunicorn app:app
    envVars:
      - key: PORT
        value: 10000

  # Frontend service
  - type: web
    name: postcode-clustering-frontend
    env: node
    buildCommand: cd frontend && npm install  # Build command for frontend
    startCommand: cd frontend && node server.js
    envVars:
      - key: BACKEND_URL
        value: "https://postcode-clustering-api.onrender.com"  # Your backend URL 