services:
  # Backend service
  - type: web
    name: postcode-clustering-backend
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && gunicorn app:app
    envVars: []  # Let Render handle the PORT assignment


  # Frontend service
  - type: web
    name: postcode-clustering-frontend
    env: node
    buildCommand: cd frontend && npm install  # Build command for frontend
    startCommand: cd frontend && node server.js
    envVars:
      - key: BACKEND_URL
        value: "https://postcode-clustering-api.onrender.com"  # Your backend URL 